### ISSUE TITLE
skm_cluster.py crashes at ramdom iteration of skm_permute

### ISSUE THREAD

**Issue by gdevenyi** [jelman/SKM_cluster#7]
This is probably the rpy2 bug you referred to in #5 

```
Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
In addition: Warning message:
In sqrt(ws[ws != 0]) : NaNs produced
Traceback (most recent call last):
  File "/opt/quarantine/SKM_cluster/31ae2bd/build/bin/skm_cluster.py", line 615, in <module>
    args.bound)
  File "/opt/quarantine/SKM_cluster/31ae2bd/build/bin/skm_cluster.py", line 558, in main
    weight_rslts, clust_rslts = run_clustering(infile, nperm, weightsum, bound)
  File "/opt/quarantine/SKM_cluster/31ae2bd/build/bin/skm_cluster.py", line 418, in run_clustering
    best_L1bound, lowest_L1bound = skm_permute(traindat)
  File "/opt/quarantine/SKM_cluster/31ae2bd/build/bin/skm_cluster.py", line 117, in skm_permute
    km_perm = sparcl.KMeansSparseCluster_permute(r_data,K=k,nperms=nperms)
  File "/opt/quarantine/anaconda/2.1.0/build/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 170, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/opt/quarantine/anaconda/2.1.0/build/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 100, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in do_one(nmeth) : NA/NaN/Inf in foreign function call (arg 1)
```

It happens at random intervals, usually somewhere between 30-40 iterations.

I'm going to dig-through and see if I can find what's going wrong.

**Comment by gdevenyi** [comment]
Digging through the R code for sparcl, it looks to me like it might be a bug in the hidden function UpdateCs, or possibly the code feeding it.

The line that specifically fails is `z <- sweep(x, 2, sqrt(ws[ws!=0]), "*")`

Which indicates to me that ws is likely negative. I'm going to try and make R spit out the data there and see what's happening inside.

**Comment by gdevenyi** [comment]
An update, I wrote up an R-script that does clustering and classification using sparcl and a mid-point score based on your work, it still crashes in the exact same way, this is actually a bug in the KMeansCluster.permute code in sparcl, not in rpy2

I think I've solved it by catching the error and going to the next iteration of my loop if it arises. If it's solved I'll see in the morning.

**Comment by jelman** [comment]
Ah, that's great news! I really appreciate your work on this - I hope to
have some time next week to work on it a bit as well.

**Comment by gdevenyi** [comment]
Here's a quick gist of what I did, if it works as intended, I'll throw up a proper project or perhaps a function that does all the work given a file.

https://gist.github.com/gdevenyi/c2e545982bcc2c93ffa4
